### ISSUE TITLE
can you pull a simpl+ usp file?

### ISSUE THREAD

**Issue by zhouji0212** [mthyden/WeatherUnderground#1]
Thanks

**Comment by mthyden** [comment]
just extract it from the compiled zip folder in the SIMPL directory, this implementation was never fully flushed out and was meant more as an example of JSON parsing through web services, I also stopped developing on it when WeatherUnderground went from a free to paid subscription model.

**Comment by zhouji0212** [comment]
thanks i will try



---Original---
